// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
// This file is automatically generated and should not be changed manually //
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
package rise.Cuda.primitives
import rise.core.DSL._
import rise.core.DSL.Type._
import rise.core._
import rise.core.types._
import rise.core.types.DataType._
import arithexpr.arithmetic._
final case class mapThreads(dim: Int) extends Builder {
  override def toString: String = "mapThreads"
  override def primitive: rise.core.Primitive = mapThreads.Primitive(dim)()
  override def apply: ToBeTyped[rise.core.Primitive] = toBeTyped(mapThreads.Primitive(dim)())
  override def unapply(arg: Expr): Boolean = arg match {
    case _: Primitive => true
    case _ => false
  }
}
object mapThreads {
  private final case class Primitive(dim: Int)(override val t: ExprType = TypePlaceholder) extends rise.core.Primitive {
    override val name: String = "mapThreads"
    override def setType(ty: ExprType): Primitive = Primitive(dim)(ty)
    override def typeScheme: ExprType = impl { (n: Nat) => impl { (s: DataType) => impl { (t: DataType) => (s ->: t) ->: ArrayType(n, s) ->: ArrayType(n, t) } } }
    override def primEq(obj: rise.core.Primitive): Boolean = obj match {
      case p: Primitive =>
        p.dim == dim && true
      case _ =>
        false
    }
  }
  def unapply(arg: rise.core.Expr): Option[Int] = arg match {
    case p: Primitive =>
      Some(p.dim)
    case _ =>
      None
  }
}
