// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
// This file is automatically generated and should not be changed manually //
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
package rise.core.primitives
import rise.core.DSL._
import rise.core.DSL.Type._
import rise.core._
import rise.core.types._
import rise.core.types.DataType._
import arithexpr.arithmetic._
final case class makeArrayWrite(n: Int) extends Builder {
  override def toString: String = "makeArrayWrite"
  override def primitive: rise.core.Primitive = makeArrayWrite.Primitive(n)()
  override def apply: ToBeTyped[rise.core.Primitive] = toBeTyped(makeArrayWrite.Primitive(n)())
  override def unapply(arg: Expr): Boolean = arg match {
    case _: Primitive => true
    case _ => false
  }
}
object makeArrayWrite {
  private final case class Primitive(n: Int)(override val t: ExprType = TypePlaceholder) extends rise.core.Primitive {
    override val name: String = "makeArrayWrite"
    override def setType(ty: ExprType): Primitive = Primitive(n)(ty)
    override def typeScheme: ExprType = impl { (dt: DataType) => Seq.fill(n)(dt).foldRight(ArrayType(n, dt): ExprType)({
      case (lhsT, rhsT) =>
        lhsT ->: rhsT
    }) }
    override def primEq(obj: rise.core.Primitive): Boolean = obj match {
      case p: Primitive =>
        p.n == n && true
      case _ =>
        false
    }
  }
  def unapply(arg: rise.core.Expr): Option[Int] = arg match {
    case p: Primitive =>
      Some(p.n)
    case _ =>
      None
  }
}
