// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
// This file is automatically generated and should not be changed manually //
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
package shine.DPIA.primitives.imperative
import arithexpr.arithmetic._
import shine.DPIA.Phrases._
import shine.DPIA.Types.DataType._
import shine.DPIA.Types._
import shine.DPIA._
final case class IdxVecAcc(val n: Nat, val dt: DataType, val index: Phrase[ExpType], val vector: Phrase[AccType]) extends AccPrimitive {
  {
    index :: expT(IndexType(n), read)
    vector :: accT(VectorType(n, dt))
  }
  override val t: AccType = accT(dt)
  override def visitAndRebuild(v: VisitAndRebuild.Visitor): IdxVecAcc = new IdxVecAcc(v.nat(n), v.data(dt), VisitAndRebuild(index, v), VisitAndRebuild(vector, v))
}
