// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
// This file is automatically generated and should not be changed manually //
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
package shine.OpenCL.primitives.functional
import arithexpr.arithmetic._
import shine.DPIA.Phrases._
import shine.DPIA.Types.DataType._
import shine.DPIA.Types._
import shine.DPIA._
final case class Map(level: shine.OpenCL.ParallelismLevel, dim: Int)(val n: Nat, val dt1: DataType, val dt2: DataType, val f: Phrase[FunType[ExpType, ExpType]], val array: Phrase[ExpType]) extends ExpPrimitive {
  {
    f :: FunType(expT(dt1, read), expT(dt2, write))
    array :: expT(ArrayType(n, dt1), read)
  }
  override val t: ExpType = expT(ArrayType(n, dt2), write)
  override def visitAndRebuild(v: VisitAndRebuild.Visitor): Map = new Map(level, dim)(v.nat(n), v.data(dt1), v.data(dt2), VisitAndRebuild(f, v), VisitAndRebuild(array, v))
  def unwrap: (Nat, DataType, DataType, Phrase[FunType[ExpType, ExpType]], Phrase[ExpType]) = (n, dt1, dt2, f, array)
}
