name: Scala CI

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout code (submodules)
        run: git submodule update --init --recursive
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Setup SBT (cache)
        uses: coursier/cache-action@v6
      - name: Setup OpenCL
        run: |
          sudo apt install ocl-icd-opencl-dev opencl-headers
          sudo apt install libpocl-dev pocl-opencl-icd
      - name: Compile
        run: sbt compile
      - name: Run tests
        run: sbt test