name: Build and deploy documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  check-documentation:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout code (submodules)
        run: git submodule update --init --recursive
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Setup SBT (cache)
        uses: coursier/cache-action@v6
      - name: Setup C++
        run: |
          sudo apt update
          sudo apt install -y cmake clang libc++-dev libc++abi-dev libxtst6 libxi6 libxrender1 libxext6
      - name: Setup OpenCL
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev opencl-headers
          sudo apt install -y libpocl-dev pocl-opencl-icd
      - name: Check documentation
        run: sbt generateRISEPrimitives docs/mdoc
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build Documentation
        working-directory: docs-website
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build

  deploy-documentation:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout code (submodules)
        run: git submodule update --init --recursive
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Setup SBT (cache)
        uses: coursier/cache-action@v6
      - name: Setup C++
        run: |
          sudo apt update
          sudo apt install -y cmake clang libc++-dev libc++abi-dev libxtst6 libxi6 libxrender1 libxext6
      - name: Setup OpenCL
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev opencl-headers
          sudo apt install -y libpocl-dev pocl-opencl-icd
      - name: Check documentation
        run: sbt generateRISEPrimitives docs/mdoc
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Release to Documentation to GitHub Pages
        working-directory: docs-website
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          yarn deploy
